### PR TITLE
Update gps.cpp

### PR DESCRIPTION
**Pull request by biomguler**
This part causes errors when computing all possible combinations.

### CODE REVIEW

**Comment by twillis209** [comment]
Hi Murat

Would you be able to tell me more about the use case in which you encountered this error? I've written the code to throw that exception because the GPS statistic is not defined in the case where the indices of the largest elements of u and v coincide: this leads to F(u) = F(v) = 1 such that the denominator of the statistic becomes F(u)F(v) - (F(u)F(v))^2 = 0.

**Comment by biomguler** [comment]
Hi Tom,
Thank you for fast reply! I understand the reason now; I just want to calculate gevd and pvlaue for all possible combination (including trait1 vs. trait1).  I obtain a result for permutation between the same trait, but in gps it gives this error because of this if statement. Is there any other solution?

**Comment by twillis209** [comment]
The `permuteAndSampleStat` function that is called by the `permuteTraitsCLI` program should just throw out permutations that end up in this error state. If you are encountering the error when running `computeGpsCLI`, then that's a result of the (unpermuted) values in the data set. I can only suggest testing the data set for this error state and throwing out values until you get a valid input. Deleting a pair of values or two shouldn't make much of a difference for a common-variant signal as there'll be other SNPs in LD.

**Comment by biomguler** [comment]
Thanks! I am getting the error when running computeGpsCLI. I understand the reason. I will try your suggestion.

**Pull request closed without merging**
